<?php
namespace Oryzone\MediaStorage\Test\Provider;

/*
 * This file is part of the Oryzone/MediaStorage package.
 *
 * (c) Luciano Mammino <lmammino@oryzone.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-07 at 09:59:41.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Oryzone\MediaStorage\Provider\Provider
     */
    protected $provider;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->provider = $this->getMockForAbstractClass('\Oryzone\MediaStorage\Provider\Provider');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testHasChangedContent()
    {
        $media = $this->getMock('\Oryzone\MediaStorage\Model\MediaInterface');
        $media->expects($this->any())
              ->method('getContent')
              ->will($this->onConsecutiveCalls(NULL, 'something'));
        $this->assertFalse($this->provider->hasChangedContent($media));
        $this->assertTrue($this->provider->hasChangedContent($media));
    }

}
