<?php
namespace Oryzone\MediaStorage\Test\Integration\Video;

use Oryzone\MediaStorage\Integration\Video\YoutubeVideoService;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-06 at 12:19:19.
 */
class YoutubeVideoServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var YoutubeVideoService
     */
    protected $youtube;

    // from http://gdata.youtube.com/feeds/api/videos/l6lYFO_tKlE
    protected static $RESPONSE = <<<EOF
<?xml version='1.0' encoding='UTF-8'?>
<entry xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xmlns:gd="http://schemas.google.com/g/2005" xmlns:yt="http://gdata.youtube.com/schemas/2007">
    <id>http://gdata.youtube.com/feeds/api/videos/l6lYFO_tKlE</id>
    <published>2012-11-08T07:38:26.000Z</published>
    <updated>2013-01-06T20:24:36.000Z</updated>
    <category scheme="http://schemas.google.com/g/2005#kind" term="http://gdata.youtube.com/schemas/2007#video" />
    <category scheme="http://gdata.youtube.com/schemas/2007/categories.cat" term="Entertainment" label="Intrattenimento" />
    <title type="text">Angry Birds Star Wars Cinematic Trailer</title>
    <content type="text">Available to download now on iOS, Google Play, PC, Amazon, Mac, Windows 8 &amp; WP8! http://download.angrybirdsstarwars.com

Angry Birds Star Wars is a new Angry Birds game set in a galaxy far, far away. Take a look at our http://angrybirds.com/starwars homepage for fan art, comics and even more animations.

Follow Angry Birds on Twitter at http://twitter.com/angrybirds
Like Angry Birds on Facebook at http://facebook.com/angrybirds
Join Angry Birds on G+ at http://plus.google.com/+AngryBirds

...And may The Birds be with you, always.</content>
    <link rel="alternate" type="text/html" href="http://www.youtube.com/watch?v=l6lYFO_tKlE&amp;feature=youtube_gdata" />
    <link rel="http://gdata.youtube.com/schemas/2007#video.responses" type="application/atom+xml" href="http://gdata.youtube.com/feeds/api/videos/l6lYFO_tKlE/responses" />
    <link rel="http://gdata.youtube.com/schemas/2007#video.related" type="application/atom+xml" href="http://gdata.youtube.com/feeds/api/videos/l6lYFO_tKlE/related" />
    <link rel="http://gdata.youtube.com/schemas/2007#mobile" type="text/html" href="http://m.youtube.com/details?v=l6lYFO_tKlE" />
    <link rel="self" type="application/atom+xml" href="http://gdata.youtube.com/feeds/api/videos/l6lYFO_tKlE" />
    <author>
        <name>RovioMobile</name>
        <uri>http://gdata.youtube.com/feeds/api/users/RovioMobile</uri>
    </author>
    <gd:comments>
        <gd:feedLink rel="http://gdata.youtube.com/schemas/2007#comments" href="http://gdata.youtube.com/feeds/api/videos/l6lYFO_tKlE/comments" countHint="3651" />
    </gd:comments>
    <yt:hd />
    <media:group>
        <media:category label="Intrattenimento" scheme="http://gdata.youtube.com/schemas/2007/categories.cat">Entertainment</media:category>
        <media:content url="http://www.youtube.com/v/l6lYFO_tKlE?version=3&amp;f=videos&amp;app=youtube_gdata" type="application/x-shockwave-flash" medium="video" isDefault="true" expression="full" duration="211" yt:format="5" />
        <media:content url="rtsp://v5.cache6.c.youtube.com/CiILENy73wIaGQlRKu3vFFiplxMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp" type="video/3gpp" medium="video" expression="full" duration="211" yt:format="1" />
        <media:content url="rtsp://v5.cache6.c.youtube.com/CiILENy73wIaGQlRKu3vFFiplxMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp" type="video/3gpp" medium="video" expression="full" duration="211" yt:format="6" />
        <media:description type="plain">Available to download now on iOS, Google Play, PC, Amazon, Mac, Windows 8 &amp; WP8! http://download.angrybirdsstarwars.com

Angry Birds Star Wars is a new Angry Birds game set in a galaxy far, far away. Take a look at our http://angrybirds.com/starwars homepage for fan art, comics and even more animations.

Follow Angry Birds on Twitter at http://twitter.com/angrybirds
Like Angry Birds on Facebook at http://facebook.com/angrybirds
Join Angry Birds on G+ at http://plus.google.com/+AngryBirds

...And may The Birds be with you, always.</media:description>
        <media:keywords />
        <media:player url="http://www.youtube.com/watch?v=l6lYFO_tKlE&amp;feature=youtube_gdata_player" />
        <media:thumbnail url="http://i.ytimg.com/vi/l6lYFO_tKlE/0.jpg" height="360" width="480" time="00:01:45.500" />
        <media:thumbnail url="http://i.ytimg.com/vi/l6lYFO_tKlE/1.jpg" height="90" width="120" time="00:00:52.750" />
        <media:thumbnail url="http://i.ytimg.com/vi/l6lYFO_tKlE/2.jpg" height="90" width="120" time="00:01:45.500" />
        <media:thumbnail url="http://i.ytimg.com/vi/l6lYFO_tKlE/3.jpg" height="90" width="120" time="00:02:38.250" />
        <media:title type="plain">Angry Birds Star Wars Cinematic Trailer</media:title>
        <yt:duration seconds="211" />
    </media:group>
    <gd:rating average="4.2352877" max="5" min="1" numRaters="44163" rel="http://schemas.google.com/g/2005#overall" />
    <yt:statistics favoriteCount="0" viewCount="17038584" />
</entry>
EOF;

    protected static $PARSED_METADATA = array (
        'id' => 'http://gdata.youtube.com/feeds/api/videos/l6lYFO_tKlE',
        'published' => '2012-11-08T07:38:26.000Z',
        'updated' => '2013-01-06T20:24:36.000Z',
        'title' => 'Angry Birds Star Wars Cinematic Trailer',
        'content' => 'Available to download now on iOS, Google Play, PC, Amazon, Mac, Windows 8 & WP8! http://download.angrybirdsstarwars.com

Angry Birds Star Wars is a new Angry Birds game set in a galaxy far, far away. Take a look at our http://angrybirds.com/starwars homepage for fan art, comics and even more animations.

Follow Angry Birds on Twitter at http://twitter.com/angrybirds
Like Angry Birds on Facebook at http://facebook.com/angrybirds
Join Angry Birds on G+ at http://plus.google.com/+AngryBirds

...And may The Birds be with you, always.',
        'tags' =>
        array (
            0 => 'Entertainment',
        ),
        'thumbnail' => 'http://img.youtube.com/vi/something/0.jpg'
    );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $buzz = $this->getMock('\Buzz\Browser');
        $buzzResponse = $this->getMock('\Buzz\Message\Response');
        $cache = $this->getMock('\Doctrine\Common\Cache\Cache');

        $buzzResponse->expects($this->any())
            ->method('getContent')
            ->will($this->returnValue(self::$RESPONSE));

        $buzz->expects($this->any())
            ->method('get')
            ->will($this->returnValue($buzzResponse));

        $this->youtube = new YoutubeVideoService($buzz, $cache);
        $this->youtube->load('something');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testLoad()
    {
        $this->assertEquals(self::$PARSED_METADATA, $this->youtube->getMetadata());
    }

    public function testGetMetaValue()
    {
        $this->assertEquals('default', $this->youtube->getMetaValue('unknown', 'default'));
    }
}
