<?php
namespace Oryzone\MediaStorage\Test\Exception;

/*
 * This file is part of the Oryzone/MediaStorage package.
 *
 * (c) Luciano Mammino <lmammino@oryzone.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Oryzone\MediaStorage\Exception\IOException;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-06 at 10:20:46.
 */
class IOExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var IOException
     */
    protected $exception;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->exception = new IOException('message', 'source');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetSource()
    {
        $this->assertEquals('source', $this->exception->getSource());
    }
}
