<?php
namespace Oryzone\MediaStorage\Test\Exception;

/*
 * This file is part of the Oryzone/MediaStorage package.
 *
 * (c) Luciano Mammino <lmammino@oryzone.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Oryzone\MediaStorage\Exception\PersistenceException;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-06 at 10:22:19.
 */
class PersistenceExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PersistenceException
     */
    protected $exception;

    protected $persistenceAdapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->persistenceAdapter = $this->getMock('\Oryzone\MediaStorage\Persistence\PersistenceAdapterInterface');
        $this->exception = new PersistenceException('message', $this->persistenceAdapter);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetPersistenceAdapter()
    {
        $this->assertEquals($this->persistenceAdapter, $this->exception->getPersistenceAdapter());
    }
}
