<?php
namespace Oryzone\MediaStorage\Test\Exception;

/*
 * This file is part of the Oryzone/MediaStorage package.
 *
 * (c) Luciano Mammino <lmammino@oryzone.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Oryzone\MediaStorage\Exception\ResourceNotFoundException;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-06 at 10:11:39.
 */
class ResourceNotFoundExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ResourceNotFoundException
     */
    protected $exception;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->exception = new ResourceNotFoundException('message', 'id');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetId()
    {
        $this->assertEquals('id', $this->exception->getId());
    }
}
