<?php
namespace Oryzone\MediaStorage\Test\Cdn;

/*
 * This file is part of the Oryzone/MediaStorage package.
 *
 * (c) Luciano Mammino <lmammino@oryzone.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Pimple;

use Oryzone\MediaStorage\Cdn\PimpleCdnFactory;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-06 at 07:59:29.
 */
class PimpleCdnFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PimpleCdnFactory
     */
    protected $factory;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->factory = new PimpleCdnFactory(new Pimple());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testAddDefinitionAndGet()
    {
        $mockCdn = $this->getMock('\Oryzone\MediaStorage\Cdn\CdnInterface');
        $this->factory->addDefinition('cdn_foo', function($c) use ($mockCdn){
            return $mockCdn;
        });
        $this->assertEquals($mockCdn, $this->factory->get('cdn_foo'));
    }

    /**
     * @expectedException \Oryzone\MediaStorage\Exception\InvalidArgumentException
     */
    public function testGetException0()
    {
        //service not defined
        $this->factory->get('foo');
    }

    /**
     * @expectedException \Oryzone\MediaStorage\Exception\InvalidConfigurationException
     */
    public function testGetException1()
    {
        // service definition does not return a cdn
        $this->factory->addDefinition('cdn_foo', function($c){
            return 'foo';
        });
        $this->factory->get('cdn_foo');
    }
}
