<?php
namespace Oryzone\MediaStorage\Test\Cdn;

/*
 * This file is part of the Oryzone/MediaStorage package.
 *
 * (c) Luciano Mammino <lmammino@oryzone.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Oryzone\MediaStorage\Cdn\RemoteCdn,
    Oryzone\MediaStorage\Model\SimpleMedia,
    Oryzone\MediaStorage\Variant\Variant;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-06 at 07:02:37.
 */
class RemoteCdnTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RemoteCdn
     */
    protected $cdn;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->cdn = new RemoteCdn;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testSetConfiguration()
    {
        $this->cdn->setConfiguration(array('base_url' => 'http://cdn.example.com/'));
    }

    /**
     * @expectedException \Oryzone\MediaStorage\Exception\InvalidArgumentException
     */
    public function testSetConfigurationException()
    {
        $this->cdn->setConfiguration(array('foo' => 'bar'));
    }

    public function testGetUrl()
    {
        $media = new SimpleMedia();
        $variant = new Variant('test');
        $variant->setFilename('file.jpg');
        $this->cdn->setConfiguration(array('base_url' => 'http://cdn.example.com/'));
        $this->assertEquals('http://cdn.example.com/file.jpg', $this->cdn->getUrl($media, $variant));
    }
}
